// Master catalog dataset for Heaven Furniture Mart bespoke pieces
// Categorized by room and timber species with dimensions and specifications

export const CATEGORIES = [
  { id: "all", labelEn: "All Pieces", labelBn: "সব আসবাব" },
  { id: "living", labelEn: "Living Room", labelBn: "লিভিং রুম" },
  { id: "dining", labelEn: "Dining Room", labelBn: "ডাইনিং রুম" },
  { id: "bedroom", labelEn: "Master Bedroom", labelBn: "মাস্টার বেডরুম" },
  { id: "showcases", labelEn: "Showcases & Storage", labelBn: "শোকেস ও আলমারি" },
  { id: "accents", labelEn: "Atelier Accents", labelBn: "স্পেশাল কালেকশন" },
];

export const TIMBERS = [
  { id: "all", labelEn: "All Timbers", labelBn: "সকল কাঠ" },
  { id: "teak", labelEn: "Chittagong Teak (সেগুন)", labelBn: "চিটাগাং সেগুন" },
  { id: "walnut", labelEn: "American Walnut (আখরোট)", labelBn: "আমেরিকান আখরোট" },
  { id: "mahogany", labelEn: "Solid Mahogany (মেহগনি)", labelBn: "মেহগনি" },
  { id: "koroi", labelEn: "Sil Koroi (সিল কড়ই)", labelBn: "সিল কড়ই" },
];

export const PRODUCTS = [
  {
    id: "imperial-sectional",
    titleEn: "Imperial L-Sectional Sofa",
    titleBn: "ইম্পেরিয়াল এল-সেকশনাল সোফা",
    category: "living",
    timber: "teak",
    timberLabelEn: "Chittagong Teak Frame",
    timberLabelBn: "চিটাগাং সেগুন কাঠের ফ্রেম",
    img: "/images/furniture-03.jpg",
    price: 98000,
    dims: "280 × 180 × 85 cm",
    leadTimeEn: "18–21 Days",
    leadTimeBn: "১৮–২১ দিন",
    joineryEn: "Mortise & Tenon · Reinforced Corners",
    joineryBn: "মর্টিস ও টেনন জয়েন্ট · রিইনফোর্সড কর্নার",
    finishEn: "High-Density Foam · Premium Linen Weave",
    finishBn: "হাই-ডেনসিটি ফোম · প্রিমিয়াম লিনেন ফেব্রিক",
    configCat: "sofa",
    descEn: "Designed for grand living rooms in Agrabad and Nasirabad. Deep seated, hand-tufted ergonomics with solid seasonal teak plinth.",
    descBn: "অভিজাত ড্রয়িংরুমের জন্য নিপুণ কারুকাজে তৈরি আরামদায়ক এল-সেকশনাল সোফা। টেকসই চিটাগাং সেগুন কাঠের ভিত্তির ওপর তৈরি।"
  },
  {
    id: "victorian-showcase",
    titleEn: "Victorian Glass Showcase & Almirah",
    titleBn: "ভিক্টোরিয়ান গ্লাস শোকেস ও আলমারি",
    category: "showcases",
    timber: "teak",
    timberLabelEn: "Carved Chittagong Teak",
    timberLabelBn: "খোদাই করা চিটাগাং সেগুন কাঠ",
    img: "https://i.ytimg.com/vi/J55q8hUvZy0/maxresdefault.jpg",
    price: 135000,
    dims: "190 × 60 × 220 cm",
    leadTimeEn: "25–30 Days",
    leadTimeBn: "২৫–৩০ দিন",
    joineryEn: "Hand-Carved Crown · Solid Dovetail Drawers",
    joineryBn: "হাতে খোদাই করা ক্রাউন · ডাভটেল ড্রয়ার",
    finishEn: "Dual-Tone Antique Gold & Italian PU Lacquer",
    finishBn: "অ্যান্টিক গোল্ড ফিনিশ ও ইতালিয়ান পিইউ বার্নিশ",
    configCat: "wardrobe",
    descEn: "The signature masterpiece from our Agrabad showroom. Featuring arched tempered glass display cabinets, intricate rococo filigree, and brass pull hardware.",
    descBn: "আমাদের শোরুমের অন্যতম সিগনেচার মাস্টারপিস। খোদাই করা রয়্যাল ডিজাইন, টেম্পারড গ্লাস এবং অ্যান্টিক ফিনিশের চমৎকার সমন্বয়।"
  },
  {
    id: "royal-dining-suite",
    titleEn: "Royal 8-Seater Dining Suite",
    titleBn: "রয়্যাল ৮-সিটার ডাইনিং স্যুট",
    category: "dining",
    timber: "walnut",
    timberLabelEn: "American Walnut & Teak",
    timberLabelBn: "আমেরিকান আখরোট ও সেগুন কাঠ",
    img: "/images/furniture-05.jpg",
    price: 165000,
    dims: "240 × 110 × 76 cm",
    leadTimeEn: "21–25 Days",
    leadTimeBn: "২১–২৫ দিন",
    joineryEn: "Butterfly Cleats · Floating Solid Plank Top",
    joineryBn: "বাটারফ্লাই ক্লিট · ফ্লোটিং সলিড প্লাঙ্ক টপ",
    finishEn: "Food-Safe Satin Hardwax Oil",
    finishBn: "ফুড-সেফ সাটিন হার্ডওয়াক্স ফিনিশ",
    configCat: "dining",
    descEn: "Substantial 45mm solid tabletop with chamfered undercut edges and eight matching high-back upholstered dining chairs.",
    descBn: "৪৫ মিমি সলিড কাঠের মজবুত টেবিলটপ এবং আরামদায়ক কুশনযুক্ত আটটি আভিজাত্যপূর্ণ চেয়ারের সমন্বয়ে তৈরি ডাইনিং সেট।"
  },
  {
    id: "sanctuary-king-bed",
    titleEn: "Sanctuary Teak King Bed",
    titleBn: "স্যাঙ্কচুয়ারি সেগুন কিং বেড",
    category: "bedroom",
    timber: "teak",
    timberLabelEn: "Chittagong Teak & Velvet",
    timberLabelBn: "চিটাগাং সেগুন ও ভেলভেট হেডবোর্ড",
    img: "/images/furniture-06.jpg",
    price: 88000,
    dims: "205 × 195 × 115 cm",
    leadTimeEn: "18–22 Days",
    leadTimeBn: "১৮–২২ দিন",
    joineryEn: "Zero-Creak Steel Interlocking Cleats",
    joineryBn: "জিরো-ক্রিক শব্দহীন স্টিল ইন্টারলকিং সিস্টেম",
    finishEn: "Natural Teak Grain PU · Acoustic Velvet Back",
    finishBn: "ন্যাচারাল সেগুন পিইউ ফিনিশ · সাউন্ড-ড্যাম্পিং ভেলভেট",
    configCat: "bed",
    descEn: "Designed for serene rest. Extra-thick solid teak side rails with an integrated fluted headboard and warm ambient brass recessed detailing.",
    descBn: "শান্ত ও আরামদায়ক ঘুমের জন্য নির্মিত আধুনিক কিং বেড। প্রিমিয়াম সেগুন কাঠের নিখুঁত পলিশ ও আরামদায়ক হেডবোর্ড।"
  },
  {
    id: "four-door-wardrobe",
    titleEn: "Heritage Bed",
    titleBn: "হেরিটেজ বেড",
    category: "bedroom",
    timber: "teak",
    timberLabelEn: "100% Solid Seasoned Teak",
    timberLabelBn: "১০০% সলিড সিজনড সেগুন কাঠ",
    img: "/images/furniture-09.jpg",
    price: 142000,
    dims: "210 × 65 × 215 cm",
    leadTimeEn: "22–26 Days",
    leadTimeBn: "২২–২৬ দিন",
    joineryEn: "Internal Cedar Lining · Soft-Close German Hinges",
    joineryBn: "সিডার লাইনিং · সফট-ক্লোজ জার্মান কব্জা",
    finishEn: "Deep Walnut Stain with Hand-Rubbed Wax",
    finishBn: "ডিপ আখরোট স্টেইন ও হ্যান্ড-রাবড ওয়াক্স",
    configCat: "wardrobe",
    descEn: "Spacious compartmentalized interior with hidden locker safe, velvet-lined watch/jewelry trays, and full-length interior bevelled dressing mirror.",
    descBn: "বিশাল স্টোরেজ স্পেস, সিক্রেট লকার, জুয়েলারি ট্রে এবং টেকসই ৪-পাল্লার আধুনিক সেগুন কাঠের আলমারি।"
  },
  {
    id: "arch-dressing-console",
    titleEn: "Atelier Dressing Console & Mirror",
    titleBn: "অ্যাটেলিয়ার ড্রেসিং কনসোল ও আর্চ মিরর",
    category: "bedroom",
    timber: "teak",
    timberLabelEn: "Chittagong Teak & Brass",
    timberLabelBn: "চিটাগাং সেগুন ও ব্রাস ডিটেইলিং",
    img: "/images/furniture-01.jpg",
    price: 54000,
    dims: "120 × 45 × 185 cm",
    leadTimeEn: "14–17 Days",
    leadTimeBn: "১৪–১৭ দিন",
    joineryEn: "Curved Steam-Bent Teak Arch Framing",
    joineryBn: "স্টিম-বেন্ট সেগুন কাঠের বাঁকানো আর্চ ফ্রেম",
    finishEn: "Matte Honey Teak with Brushed Brass Accents",
    finishBn: "ম্যাট হানি সেগুন ফিনিশ ও ব্রাশড ব্রাস হ্যান্ডেল",
    configCat: "chair",
    descEn: "Sleek floating aesthetic with three velvet-lined drawers, curved solid teak mirror surround, and integrated low-glare warm backlit LED channel.",
    descBn: "বেডরুমের আভিজাত্য বাড়াতে আর্চ আকৃতির গ্লাস, তিনটি ড্রয়ার এবং খাঁটি সেগুন কাঠে তৈরি ড্রেসিং কনসোল।"
  },
  {
    id: "victorian-coffee-table",
    titleEn: "Victorian Hand-Carved Center Table",
    titleBn: "ভিক্টোরিয়ান খোদাই করা সেন্টার টেবিল",
    category: "living",
    timber: "teak",
    timberLabelEn: "Master Carved Teak Plinth",
    timberLabelBn: "খোদাই করা সলিড সেগুন কাঠ",
    img: "https://i.ytimg.com/vi/95QrFvVcLXI/maxresdefault.jpg",
    price: 46000,
    dims: "135 × 85 × 46 cm",
    leadTimeEn: "14–18 Days",
    leadTimeBn: "১৪–১৮ দিন",
    joineryEn: "Interlocking Cross Stretcher Base",
    joineryBn: "ক্রস-স্ট্রেচার ইন্টারলকিং শক্ত বেস",
    finishEn: "Antique Walnut Glaze with 10mm Beveled Glass",
    finishBn: "অ্যান্টিক আখরোট গ্লেজ ও ১০ মিমি বেভেলড গ্লাস",
    configCat: "dining",
    descEn: "Featured in our showroom video showcase. Intricate lion-paw cabriole legs, scalloped floral aprons, and tempered protective glass top.",
    descBn: "আমাদের শোরুমের বিশেষ ভিক্টোরিয়ান ডিজাইনের সেন্টার টেবিল। নিপুণ হাতের ফুল ও নকশার সাথে মজবুত বেভেলড গ্লাস।"
  },
  {
    id: "luxury-balcony-swing",
    titleEn: "Suspended Atelier Balcony Swing",
    titleBn: "সাসপেন্ডেড অ্যাটেলিয়ার বারান্দা দোলনা",
    category: "accents",
    timber: "mahogany",
    timberLabelEn: "Weather-Resistant Mahogany & Rattan",
    timberLabelBn: "মেহগনি কাঠ ও প্রাকৃতিক বেত",
    img: "/images/furniture-05.jpg",
    price: 62000,
    dims: "140 × 75 × 60 cm",
    leadTimeEn: "16–20 Days",
    leadTimeBn: "১৬–২০ দিন",
    joineryEn: "Marine-Grade 316 Stainless Steel Swivels",
    joineryBn: "মেরিন-গ্রেড ৩১৬ স্টেইনলেস স্টিল সুইভেল",
    finishEn: "Natural Cane Woven Mesh · Outdoor-Grade Fabric",
    finishBn: "হাতে বোনা প্রাকৃতিক বেত ও ওয়েদারপ্রুফ কুশন",
    configCat: "chair",
    descEn: "A sanctuary for penthouse verandas in Khulshi. Deep lounging proportion with woven rattan side panels and heavy-gauge solid brass ceiling hooks.",
    descBn: "বারান্দা বা লিভিং রুমের জন্য বিশেষভাবে তৈরি বিলাসবহুল কাঠের ঝুলন্ত দোলনা। আরামদায়ক কুশন ও মজবুত সুইভেল।"
  },
  {
    id: "executive-study-desk",
    titleEn: "Diplomat Executive Study Desk",
    titleBn: "ডিপ্লোম্যাট এক্সিকিউটিভ স্টাডি ডেস্ক",
    category: "accents",
    timber: "walnut",
    timberLabelEn: "Solid American Walnut",
    timberLabelBn: "সলিড আমেরিকান আখরোট কাঠ",
    img: "/images/furniture-10.jpg",
    price: 82000,
    dims: "170 × 80 × 76 cm",
    leadTimeEn: "18–22 Days",
    leadTimeBn: "১৮–২২ দিন",
    joineryEn: "Double Dovetail Drawer Construction",
    joineryBn: "ডাবল ডাভটেল ড্রয়ার জয়েন্ট",
    finishEn: "Full-Grain Italian Leather Writing Inlay",
    finishBn: "ইতালিয়ান লেদার রাইটিং প্যাড ইনলে",
    configCat: "dining",
    descEn: "Built for senior professionals, doctors, and business heads. Integrated magnetic wire-management conduit and discreet locking drawer.",
    descBn: "অভিজাত অফিস বা স্টাডি রুমের জন্য নিখুঁত মাপের এক্সিকিউটিভ ডেস্ক। প্রিমিয়াম লেদার প্যাড ও কেবল ম্যানেজমেন্ট সিস্টেম।"
  },
  {
    id: "marble-dining-credenza",
    titleEn: "Palace Dining Credenza & Sideboard",
    titleBn: "প্যালেস ডাইনিং সাইডবোর্ড ও ক্রেডেনজা",
    category: "dining",
    timber: "teak",
    timberLabelEn: "Chittagong Teak & Marble Top",
    timberLabelBn: "চিটাগাং সেগুন ও মার্বেল টপ",
    img: "/images/furniture-02.jpg",
    price: 92000,
    dims: "180 × 50 × 88 cm",
    leadTimeEn: "18–24 Days",
    leadTimeBn: "১৮–২৪ দিন",
    joineryEn: "Fluted Tambour Sliding Front Doors",
    joineryBn: "বাঁকানো ট্যাম্বুর স্লাইডিং কাঠের ডোর",
    finishEn: "Honed Italian Botticino Marble Surface",
    finishBn: "ইতালিয়ান বত্তিচিনো মার্বেল টপ ফিনিশ",
    configCat: "wardrobe",
    descEn: "The essential dining room companion. Natural cool marble surface perfect for warm serving dishes, with ample internal cutlery and dinnerware storage.",
    descBn: "ডাইনিং স্পেসকে পূর্ণাঙ্গ করতে প্রিমিয়াম মার্বেল টপযুক্ত সাইডবোর্ড। থালাবাসন ও ক্রোকারিজ রাখার পর্যাপ্ত সুসজ্জিত ড্রয়ার।"
  },
  {
    id: "royal-velvet-divan",
    titleEn: "Heritage Royal Divan",
    titleBn: "হেরিটেজ রয়্যাল দিওয়ান",
    category: "living",
    timber: "teak",
    timberLabelEn: "Hand-Turned Teak Legs",
    timberLabelBn: "হাতে ঘোরানো সেগুন কাঠের পায়া",
    img: "https://i.ytimg.com/vi/lxhZF9s7fhY/maxresdefault.jpg",
    price: 58000,
    dims: "195 × 85 × 72 cm",
    leadTimeEn: "15–18 Days",
    leadTimeBn: "১৫–১৮ দিন",
    joineryEn: "Traditional Pegged Mortise & Tenon",
    joineryBn: "ঐতিহ্যবাহী পেগড মর্টিস ও টেনন জয়েন্ট",
    finishEn: "Emerald Velvet Upholstery with Brass Studs",
    finishBn: "পান্না সবুজ ভেলভেট ফেব্রিক ও ব্রাস স্টাড",
    configCat: "sofa",
    descEn: "Classic Bangladeshi hospitality piece. Single-arm curved silhouette with bolster pillows, ideal beneath living room windows or foyer walls.",
    descBn: "ঐতিহ্যবাহী বাঙালি আতিথেয়তার অন্যতম অনুষঙ্গ দিওয়ান। ড্রয়িং রুমের শোভা বাড়াতে আরামদায়ক ভেলভেট ও শক্ত কাঠের ফ্রেম।"
  },
  {
    id: "louvered-tv-console",
    titleEn: "Louvered Media Wall Credenza",
    titleBn: "লুভার্ড টিভি ও মিডিয়া কনসোল",
    category: "living",
    timber: "koroi",
    timberLabelEn: "Seasoned Sil Koroi Hardwood",
    timberLabelBn: "সিজনড সিল কড়ই কাঠ",
    img: "/images/furniture-01.jpg",
    price: 49000,
    dims: "200 × 42 × 52 cm",
    leadTimeEn: "14–17 Days",
    leadTimeBn: "১৪–১৭ দিন",
    joineryEn: "IR-Acoustic Slatting for Hidden Electronics",
    joineryBn: "সাউন্ড ও রিমোট সিগন্যাল ফ্রেন্ডলি স্ল্যাট ডিজাইন",
    finishEn: "Natural Earth Stain Matte Protective Seal",
    finishBn: "ন্যাচারাল আর্থ স্টেইন ম্যাট সিল",
    configCat: "wardrobe",
    descEn: "Modern acoustic louvered front allows remote control IR signals to pass through while keeping amplifiers, set-top boxes, and consoles concealed.",
    descBn: "টিভি ও সাউন্ড সিস্টেম সুন্দরভাবে গুছিয়ে রাখার আধুনিক মিডিয়া ইউনিট। স্ল্যাট ডিজাইনের কারণে বন্ধ অবস্থাতেও রিমোট কাজ করে।"
  }
];
